### PR TITLE
Configurable max pages depth

### PR DESCRIPTION
**Pull request by lilfaf**
This is related to https://github.com/Permigo/Spina/commit/9165742a84fe6b4d23c5a7445d247e51acf52ac6

### CODE REVIEW

**Comment by Bramjetten** [comment]
I believe we should get the initialization of nestable out of Spina-template and into the Spina gem. This way spina-template is still usable as a separate gem for other projects that don't use Spina CMS.

**Comment by lilfaf** [comment]
Do you want to move the initialization only or the entire dependency ? In any case, it sounds good to me.

**Comment by Bramjetten** [comment]
I'm thinking just the initialization. Thoughts?

**Comment by lilfaf** [comment]
I have not much to say here. I perfectly agree with the idea of making nestable plugin a soft dependency of Spina. :+1:

**Pull request merged**
